FROM tomcat:{{ tomcat_image_version }}
# Remove default ROOT application
RUN ["rm", "-fr", "/usr/local/tomcat/webapps/ROOT"]

COPY grails-petclinic/target/petclinic-4.0.war /usr/local/tomcat/webapps/ROOT.war
